# Generated by Django 3.2 on 2023-02-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
